spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/livqualitidb
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

amazon:
  aws:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}


app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiry-time: ${JWT_EXPIRY_TIME}