#spring.application.name=backend
spring:
  application:
    name: backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.wfarooq.backend: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"


